# Generated by Django 5.0.3 on 2024-07-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='confidence',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
    ]
